fix: add support for passing null in prefix
terraform-ibm-modules/terraform-ibm-landing-zone-vpc pull request #605
Opened 2023-08-18 10:40 UTC by Khuzaima05

### Description
Added  support for passing null in prefix

###issue : https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/598

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

2023-08-18 10:40 UTC, Khuzaima05 commented
/run pipeline

2023-08-18 11:15 UTC, ocofaigh requested changes
@Khuzaima05 see comments. Can you also please paste a terraform plan output when prefix is set to null ?

2023-08-18 11:15 UTC, ocofaigh commented on variables.tf
> +  description = "The prefix that you would like to append to your resources. It supports passing null"
Maybe say this instead:

> Explicitly set to null if you do not wish to use a prefix.

2023-08-18 11:15 UTC, ocofaigh commented on examples/landing_zone/main.tf
> +  transit_gateway_name      = var.prefix != null ? "${var.prefix}-tg" : "tg"
I would not add this support to the example. The example should always use a prefix (so we avoid name clashes during test runs in our account)

2023-08-18 11:15 UTC, ocofaigh commented on examples/default/main.tf
> +  bucket_name          = var.prefix != null ? "${var.prefix}-vpc-logs-cos-bucket" : "vpc-logs-cos-bucket"
I would not add this support to the example. The example should always use a prefix (so we avoid name clashes during test runs in our account)

2023-08-21 10:04 UTC, Khuzaima05 commented
> @Khuzaima05 see comments. Can you also please paste a terraform plan output when prefix is set to null ?

<img width="1109" alt="Screenshot 2023-08-21 at 3 33 56 PM" src="https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/assets/56439894/4d24983c-7d40-4825-afa8-e0cab699446e">

2023-08-21 11:16 UTC, Khuzaima05 commented
/run pipeline

2023-08-21 12:05 UTC, ocofaigh commented
So @Khuzaima05 from the screenshot (which looks like its a plan from an existing terraform state), the current code is giving an error. Are you looking in to that?

2023-08-22 06:50 UTC, Khuzaima05 commented
/run pipeline

2023-08-22 07:01 UTC, Khuzaima05 commented
/run pipeline

2023-08-22 08:11 UTC, Khuzaima05 commented
> So @Khuzaima05 from the screenshot (which looks like its a plan from an existing terraform state), the current code is giving an error. Are you looking in to that?

This error got resolved.

2023-08-22 08:13 UTC, Khuzaima05 commented
> > @Khuzaima05 see comments. Can you also please paste a terraform plan output when prefix is set to null ?
> 
> <img alt="Screenshot 2023-08-21 at 3 33 56 PM" width="1109" src="https://user-images.githubusercontent.com/56439894/261990696-4d24983c-7d40-4825-afa8-e0cab699446e.png">

Recieving the same error in plan if we pass `NULL` in example.

2023-08-22 10:53 UTC, ocofaigh commented on examples/default/main.tf
> +  name              = var.prefix != null ? "${var.prefix}-vpc-logs-cos" : "vpc-logs-cos"
@Khuzaima05 please remove this change. This does not have to support passing prefix as null. Infact prefix is required in the **example**

2023-08-22 10:53 UTC, ocofaigh commented on examples/default/main.tf
> +  bucket_name          = var.prefix != null ? "${var.prefix}-vpc-logs-cos-bucket" : "vpc-logs-cos-bucket"
@Khuzaima05 please remove this change. This does not have to support passing prefix as null. Infact prefix is required in the **example**

2023-08-23 08:39 UTC, ocofaigh commented
@Khuzaima05 Passing `null` for prefix does not work. I cloned your branch and updated the main.tf default example like this:
```
module "slz_vpc" {
  source                                 = "../../"
  resource_group_id                      = var.resource_group != null ? data.ibm_resource_group.existing_resource_group[0].id : ibm_resource_group.resource_group[0].id
  region                                 = var.region
  name                                   = var.name
  prefix                                 = null
  tags                                   = var.resource_tags
  access_tags                            = var.access_tags
  enable_vpc_flow_logs                   = var.enable_vpc_flow_logs
  create_authorization_policy_vpc_to_cos = var.create_authorization_policy_vpc_to_cos
  existing_cos_instance_guid             = ibm_resource_instance.cos_instance[0].guid
  existing_storage_bucket_name           = ibm_cos_bucket.cos_bucket[0].bucket_name
  address_prefixes                       = var.address_prefixes
  network_cidrs                          = var.network_cidrs
}
```

The error I get is:
```
│ Error: Invalid template interpolation value
│ 
│   on ../../dynamic_values.tf line 7, in module "dynamic_values":
│    7:   prefix               = "${var.prefix}-${var.name}"
│     ├────────────────
│     │ var.prefix is null
│ 
│ The expression result is null. Cannot include a null value in a string template.
```

2023-08-23 08:47 UTC, ocofaigh commented
Looks like there are 3 more places you need to make the change to support passing `null` for prefix:

- https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/blob/25cfdcaeedd851224c3a04c1492e722859307c30/dynamic_values.tf#L7
- https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/blob/25cfdcaeedd851224c3a04c1492e722859307c30/dynamic_values/main.tf#L20
- https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/blob/25cfdcaeedd851224c3a04c1492e722859307c30/network_acls.tf#L164

Please update these and show me the output of your test when passing `null` for prefix

2023-08-24 07:42 UTC, ocofaigh commented
@Khuzaima05 This is NOT how to test it. You do not want the pass `null` for the prefix variable in the example. you want you pass null into the VPC module directly. Just like I showed you in https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/pull/605#issuecomment-1689534168

2023-08-24 09:43 UTC, Khuzaima05 commented
> 



> @Khuzaima05 This is NOT how to test it. You do not want the pass `null` for the prefix variable in the example. you want you pass null into the VPC module directly. Just like I showed you in [#605 (comment)](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/pull/605#issuecomment-1689534168)

@ocofaigh , I tested accordingly, here is the terraform output (default example) :
<img width="1049" alt="Screenshot 2023-08-24 at 3 11 21 PM" src="https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/assets/56439894/195820d9-6a23-47c2-aebf-4588e7c1771d">

2023-08-24 11:10 UTC, ocofaigh commented
Yes thanks, please push the code updates @Khuzaima05

2023-08-24 18:21 UTC, Khuzaima05 commented
/run pipeline

2023-08-24 19:18 UTC, Khuzaima05 commented
/run pipeline

2023-08-25 09:22 UTC, Khuzaima05 commented
/run pipeline

2023-08-25 09:57 UTC, ocofaigh requested changes
@Khuzaima05 your not supposed to commit the changes you made to test `null` in the examples. Thats only for local testing. Please revert them

2023-08-25 11:07 UTC, Khuzaima05 commented
/run pipeline

2023-08-25 11:27 UTC, Khuzaima05 commented
@ocofaigh Upgrade test is failing, Can I skip that.

2023-08-25 13:55 UTC, Khuzaima05 commented
> @Khuzaima05 no - upgrade test should not fail with the changes being made in this PR - we need to figure out why its failing

@ocofaigh  Pipeline passed, Could you please review and merge.

2023-08-25 14:06 UTC, ocofaigh approved these changes

2023-08-25 14:06 UTC, merged

2023-08-25 14:08 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 7.4.2 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/releases/tag/v7.4.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: