feat: enhance naming for vpc resources and fix prefix checks
terraform-ibm-modules/terraform-ibm-landing-zone-vpc pull request #697
Opened 2023-12-22 13:51 UTC by rajatagarwal-ibm

### Description

Addresses:
* https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/678
* https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/issues/677
* 
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-01-02 11:01 UTC, rajatagarwal-ibm commented
There are some errors encountered during the upgrade test run. 

Public Gateway naming:
```
DIFF:
        	            	  Before: 
        	            		{"name":"slz-vpc-upg-yxie1c-vpc-public-gateway-zone-1"}
        	            	  After: 
        	            		{"name":"slz-vpc-upg-yxie1c-public-gateway-zone-1"}
```

Flow logs naming:
```
DIFF:
        	            	  Before: 
        	            		{"name":"slz-vpc-upg-yxie1c-vpc-logs"}
        	            	  After: 
        	            		{"name":"slz-vpc-upg-yxie1c-logs"}
```

VPC naming:

```
DIFF:
        	            	  Before: 
        	            		{"name":"slz-vpc-upg-yxie1c-vpc-vpc"}
        	            	  After: 
        	            		{"name":"slz-vpc-upg-yxie1c-vpc"}
```

There are some other errors like `Error getting diff: missing 'before' or 'after' key in JSON`, `SECURE_VALUE_HIDDEN_HASH value change` etc.

2024-01-02 11:01 UTC, rajatagarwal-ibm commented
/run pipeline

2024-01-02 11:34 UTC, ocofaigh commented
@rajatagarwal-ibm The ones that failed with `Error getting diff: missing 'before' or 'after' key in JSON` are valid breaking changes. It means there has been a destroy identified, which is a breaking change. We cannot skip the upgrade test here. We neef to ensure there are NO destroys. For example, I see:

```
Messages:   	Resource(s) identified to be destroyed 
        	            	Name: address_prefixes
        	            	Address: module.slz_vpc.ibm_is_vpc_address_prefix.address_prefixes["slz-vpc-upg-yxie1c-vpc-zone-3-1"]
        	            	Actions: [delete]
        	            	DIFF:
        	            	Error getting diff: missing 'before' or 'after' key in JSON
```

2024-01-03 10:41 UTC, rajatagarwal-ibm commented
/run pipeline

2024-01-03 10:52 UTC, rajatagarwal-ibm commented
List of Resources Identified for Destruction:

1. Resource Type: address_prefixes
   Name: address_prefixes
   Address: module.slz_vpc.ibm_is_vpc_address_prefix.address_prefixes["slz-vpc-upg-yxie1c-vpc-zone-3-1"]
   Actions: [delete]

2. Resource Type: subnet
   Name: subnet
   Address: module.slz_vpc.ibm_is_subnet.subnet["slz-vpc-upg-yxie1c-vpc-subnet-b"]
   Actions: [delete]

3. Resource Type: address_prefixes
   Name: address_prefixes
   Address: module.slz_vpc.ibm_is_vpc_address_prefix.address_prefixes["slz-vpc-upg-yxie1c-vpc-zone-1-1"]
   Actions: [delete]

4. Resource Type: address_prefixes
   Name: address_prefixes
   Address: module.slz_vpc.ibm_is_vpc_address_prefix.address_prefixes["slz-vpc-upg-yxie1c-vpc-zone-2-1"]
   Actions: [delete]

5. Resource Type: subnet
   Name: subnet
   Address: module.slz_vpc.ibm_is_subnet.subnet["slz-vpc-upg-yxie1c-vpc-subnet-a"]
   Actions: [delete]

6. Resource Type: subnet
   Name: subnet
   Address: module.slz_vpc.ibm_is_subnet.subnet["slz-vpc-upg-yxie1c-vpc-subnet-c"]
   Actions: [delete]

Upon investigation, it was discovered that the naming convention for "address_prefixes" and "subnet" has changed from including "vpc" to excluding it. The default example removed the "name = var.name" field, causing the absence of "vpc" in the name. Reintroducing this field resolves the issue.


**PS:** I have unskipped upgrade tests.

2024-01-03 11:01 UTC, ocofaigh reviewed
I think Allen said before that he would prefer instead of using "var.name" in variable descriptions, we should say "`name` input variable".

Since the logic here is quite confusing, I think it might help if you could attach a terraform plan which shows how everything gets named for all of the possible use cases..

1. use `prefix` and `name` and none of the new variables
2. use `name` only (no prefix, none of the new variable)
3. use `prefix` only (no name, none of the new variables)
4. use all of the new variables and set `prefix` and `name` to null
5. set a value for `prefix` and use all of the new variables. Do not use `name`
6. set a value for `name` and use all of the new variables. Do not use `prefix`

2024-01-03 11:52 UTC, rajatagarwal-ibm commented
## Use case # 1: Use `prefix` and `name`, no new variables

```

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # module.resource_group.ibm_resource_group.resource_group[0] will be created
  + resource "ibm_resource_group" "resource_group" {
      + created_at          = (known after apply)
      + crn                 = (known after apply)
      + default             = (known after apply)
      + id                  = (known after apply)
      + name                = "prefix-resource-group"
      + payment_methods_url = (known after apply)
      + quota_id            = (known after apply)
      + quota_url           = (known after apply)
      + resource_linkages   = (known after apply)
      + state               = (known after apply)
      + teams_url           = (known after apply)
      + updated_at          = (known after apply)
    }

  # module.slz_vpc.data.ibm_is_vpc_address_prefixes.get_address_prefixes will be read during apply
  # (config refers to values not yet known)
 <= data "ibm_is_vpc_address_prefixes" "get_address_prefixes" {
      + address_prefixes = (known after apply)
      + id               = (known after apply)
      + vpc              = (known after apply)
    }

  # module.slz_vpc.ibm_is_network_acl.network_acl["vpc-acl"] will be created
  + resource "ibm_is_network_acl" "network_acl" {
      + access_tags             = (known after apply)
      + crn                     = (known after apply)
      + id                      = (known after apply)
      + name                    = "prefix-vpc-acl"
      + resource_controller_url = (known after apply)
      + resource_crn            = (known after apply)
      + resource_group          = (known after apply)
      + resource_group_name     = (known after apply)
      + resource_name           = (known after apply)
      + tags                    = (known after apply)
      + vpc                     = (known after apply)
    }

  # module.slz_vpc.ibm_is_public_gateway.gateway["zone-1"] will be created
  + resource "ibm_is_public_gateway" "gateway" {
      + access_tags             = (known after apply)
      + crn                     = (known after apply)
      + floating_ip             = (known after apply)
      + id                      = (known after apply)
      + name                    = "prefix-name-public-gateway-zone-1"
      + resource_controller_url = (known after apply)
      + resource_crn            = (known after apply)
      + resource_group          = (known after apply)
      + resource_group_name     = (known after apply)
      + resource_name           = (known after apply)
      + resource_status         = (known after apply)
      + status                  = (known after apply)
      + tags                    = (known after apply)
      + vpc                     = (known after apply)
      + zone                    = "us-south-1"
    }

  # module.slz_vpc.ibm_is_subnet.subnet["prefix-name-subnet-a"] will be created
  + resource "ibm_is_subnet" "subnet" {
      + access_tags                  = (known after apply)
      + available_ipv4_address_count = (known after apply)
      + crn                          = (known after apply)
      + id                           = (known after apply)
      + ip_version                   = "ipv4"
      + ipv4_cidr_block              = "10.10.10.0/24"
      + name                         = "prefix-name-subnet-a"
      + network_acl                  = (known after apply)
      + public_gateway               = (known after apply)
      + resource_controller_url      = (known after apply)
      + resource_crn                 = (known after apply)
      + resource_group               = (known after apply)
      + resource_group_name          = (known after apply)
      + resource_name                = (known after apply)
      + resource_status              = (known after apply)
      + routing_table                = (known after apply)
      + status                       = (known after apply)
      + tags                         = (known after apply)
      + total_ipv4_address_count     = (known after apply)
      + vpc                          = (known after apply)
      + zone                         = "us-south-1"
    }

  # module.slz_vpc.ibm_is_vpc.vpc[0] will be created
  + resource "ibm_is_vpc" "vpc" {
      + access_tags                 = (known after apply)
      + address_prefix_management   = "manual"
      + classic_access              = false
      + crn                         = (known after apply)
      + cse_source_addresses        = (known after apply)
      + default_network_acl         = (known after apply)
      + default_network_acl_crn     = (known after apply)
      + default_network_acl_name    = (known after apply)
      + default_routing_table       = (known after apply)
      + default_routing_table_name  = (known after apply)
      + default_security_group      = (known after apply)
      + default_security_group_crn  = (known after apply)
      + default_security_group_name = (known after apply)
      + health_reasons              = (known after apply)
      + health_state                = (known after apply)
      + id                          = (known after apply)
      + name                        = "prefix-name-vpc"
      + no_sg_acl_rules             = false
      + resource_controller_url     = (known after apply)
      + resource_crn                = (known after apply)
      + resource_group              = (known after apply)
      + resource_group_name         = (known after apply)
      + resource_name               = (known after apply)
      + resource_status             = (known after apply)
      + security_group              = (known after apply)
      + status                      = (known after apply)
      + subnets                     = (known after apply)
      + tags                        = (known after apply)

      + dns {
          + enable_hub               = false
          + resolution_binding_count = (known after apply)
        }
    }

  # module.slz_vpc.ibm_is_vpc_address_prefix.subnet_prefix["prefix-name-subnet-a"] will be created
  + resource "ibm_is_vpc_address_prefix" "subnet_prefix" {
      + address_prefix = (known after apply)
      + cidr           = "10.10.10.0/24"
      + has_subnets    = (known after apply)
      + id             = (known after apply)
      + is_default     = false
      + name           = "prefix-name-subnet-a"
      + related_crn    = (known after apply)
      + vpc            = (known after apply)
      + zone           = "us-south-1"
    }

Plan: 6 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + vpc_crn = (known after apply)
  + vpc_id  = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.

```

## Use case # 2: Use `prefix`, no `name` or any new variable

```

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # module.resource_group.ibm_resource_group.resource_group[0] will be created
  + resource "ibm_resource_group" "resource_group" {
      + created_at          = (known after apply)
      + crn                 = (known after apply)
      + default             = (known after apply)
      + id                  = (known after apply)
      + name                = "prefix-resource-group"
      + payment_methods_url = (known after apply)
      + quota_id            = (known after apply)
      + quota_url           = (known after apply)
      + resource_linkages   = (known after ap [...]

2024-01-03 11:55 UTC, rajatagarwal-ibm commented
/run pipeline

2024-01-03 15:27 UTC, rajatagarwal-ibm commented
As discussed with @ocofaigh, made `name` mandatory input. That means need to update the following code:

1. Made `name` mandatory at the root module
2. Removed validation to check either `name` or `prefix` must be passed.
3. Updated all the naming logic to accommodate change when the name is always passed. 
4. Updated variable description to use variable references as `var-name` rather than var.var-name.

2024-01-03 15:29 UTC, rajatagarwal-ibm commented
/run pipeline

2024-01-03 15:40 UTC, rajatagarwal-ibm commented
## Use case # 1:  use prefix and name and none of the new variables

```

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # module.resource_group.ibm_resource_group.resource_group[0] will be created
  + resource "ibm_resource_group" "resource_group" {
      + created_at          = (known after apply)
      + crn                 = (known after apply)
      + default             = (known after apply)
      + id                  = (known after apply)
      + name                = "basic-slz-vpc-resource-group"
      + payment_methods_url = (known after apply)
      + quota_id            = (known after apply)
      + quota_url           = (known after apply)
      + resource_linkages   = (known after apply)
      + state               = (known after apply)
      + teams_url           = (known after apply)
      + updated_at          = (known after apply)
    }

  # module.slz_vpc.data.ibm_is_vpc_address_prefixes.get_address_prefixes will be read during apply
  # (config refers to values not yet known)
 <= data "ibm_is_vpc_address_prefixes" "get_address_prefixes" {
      + address_prefixes = (known after apply)
      + id               = (known after apply)
      + vpc              = (known after apply)
    }

  # module.slz_vpc.ibm_is_network_acl.network_acl["vpc-acl"] will be created
  + resource "ibm_is_network_acl" "network_acl" {
      + access_tags             = (known after apply)
      + crn                     = (known after apply)
      + id                      = (known after apply)
      + name                    = "basic-slz-vpc-vpc-vpc-acl"
      + resource_controller_url = (known after apply)
      + resource_crn            = (known after apply)
      + resource_group          = (known after apply)
      + resource_group_name     = (known after apply)
      + resource_name           = (known after apply)
      + tags                    = (known after apply)
      + vpc                     = (known after apply)
    }

  # module.slz_vpc.ibm_is_public_gateway.gateway["zone-1"] will be created
  + resource "ibm_is_public_gateway" "gateway" {
      + access_tags             = (known after apply)
      + crn                     = (known after apply)
      + floating_ip             = (known after apply)
      + id                      = (known after apply)
      + name                    = "basic-slz-vpc-vpc-public-gateway-zone-1"
      + resource_controller_url = (known after apply)
      + resource_crn            = (known after apply)
      + resource_group          = (known after apply)
      + resource_group_name     = (known after apply)
      + resource_name           = (known after apply)
      + resource_status         = (known after apply)
      + status                  = (known after apply)
      + tags                    = (known after apply)
      + vpc                     = (known after apply)
      + zone                    = "us-south-1"
    }

  # module.slz_vpc.ibm_is_subnet.subnet["basic-slz-vpc-vpc-subnet-a"] will be created
  + resource "ibm_is_subnet" "subnet" {
      + access_tags                  = (known after apply)
      + available_ipv4_address_count = (known after apply)
      + crn                          = (known after apply)
      + id                           = (known after apply)
      + ip_version                   = "ipv4"
      + ipv4_cidr_block              = "10.10.10.0/24"
      + name                         = "basic-slz-vpc-vpc-subnet-a"
      + network_acl                  = (known after apply)
      + public_gateway               = (known after apply)
      + resource_controller_url      = (known after apply)
      + resource_crn                 = (known after apply)
      + resource_group               = (known after apply)
      + resource_group_name          = (known after apply)
      + resource_name                = (known after apply)
      + resource_status              = (known after apply)
      + routing_table                = (known after apply)
      + status                       = (known after apply)
      + tags                         = (known after apply)
      + total_ipv4_address_count     = (known after apply)
      + vpc                          = (known after apply)
      + zone                         = "us-south-1"
    }

  # module.slz_vpc.ibm_is_vpc.vpc[0] will be created
  + resource "ibm_is_vpc" "vpc" {
      + access_tags                 = (known after apply)
      + address_prefix_management   = "manual"
      + classic_access              = false
      + crn                         = (known after apply)
      + cse_source_addresses        = (known after apply)
      + default_network_acl         = (known after apply)
      + default_network_acl_crn     = (known after apply)
      + default_network_acl_name    = (known after apply)
      + default_routing_table       = (known after apply)
      + default_routing_table_name  = (known after apply)
      + default_security_group      = (known after apply)
      + default_security_group_crn  = (known after apply)
      + default_security_group_name = (known after apply)
      + health_reasons              = (known after apply)
      + health_state                = (known after apply)
      + id                          = (known after apply)
      + name                        = "basic-slz-vpc-vpc-vpc"
      + no_sg_acl_rules             = false
      + resource_controller_url     = (known after apply)
      + resource_crn                = (known after apply)
      + resource_group              = (known after apply)
      + resource_group_name         = (known after apply)
      + resource_name               = (known after apply)
      + resource_status             = (known after apply)
      + security_group              = (known after apply)
      + status                      = (known after apply)
      + subnets                     = (known after apply)
      + tags                        = (known after apply)

      + dns {
          + enable_hub               = false
          + resolution_binding_count = (known after apply)
        }
    }

  # module.slz_vpc.ibm_is_vpc_address_prefix.subnet_prefix["basic-slz-vpc-vpc-subnet-a"] will be created
  + resource "ibm_is_vpc_address_prefix" "subnet_prefix" {
      + address_prefix = (known after apply)
      + cidr           = "10.10.10.0/24"
      + has_subnets    = (known after apply)
      + id             = (known after apply)
      + is_default     = false
      + name           = "basic-slz-vpc-vpc-subnet-a"
      + related_crn    = (known after apply)
      + vpc            = (known after apply)
      + zone           = "us-south-1"
    }

Plan: 6 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + vpc_crn = (known after apply)
  + vpc_id  = (known after apply)

─────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't
guarantee to take exactly these actions if you run "terraform apply" now.
```
## Use case # 2: use name only (no prefix, none of the new variable)
```

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # module.resource_group.ibm_resource_group.resource_group[0] will be created
  + resource "ibm_resource_group" "resource_group" {
      + created_at          = (known after apply)
      + crn                 = (known after apply)
      + default             = (known after apply)
      + id                  = (known after apply)
      + name                = "basic-slz-vpc-resource-group"
      + payment_methods_url = (known after apply)
      + quota_id            = (known after apply)
      + quota_url    [...]

2024-01-03 16:02 UTC, rajatagarwal-ibm commented
/run pipeline

2024-01-03 16:31 UTC, ocofaigh requested changes
Almost there - last few comments

2024-01-03 16:31 UTC, ocofaigh commented on variables.tf
> +    error_message = "`resolver_type` either be null, or set to the string 'system' or 'manual'."
missing the word "can": 

`resolver_type` **can** either be ....

2024-01-03 16:31 UTC, ocofaigh commented on variables.tf
> +  description = "If `create_vpc` is true, this string names both the VPC and associated resources. If false, it names only the associated resources."
Used for the naming of the VPC (if `create_vpc` is set to true), as well as in the naming for any resources created inside the VPC (unless using one of the optional variables for explicit control over naming).

2024-01-03 16:31 UTC, ocofaigh commented on variables.tf
> +  description = "The value that you would like to prefix to the name of the resources provisioned by this module. Explicitly set to null if you do not wish to use a prefix."
Also add this:
This value is ignored is using one of the optional variables for explicit control over naming

2024-01-03 17:03 UTC, rajatagarwal-ibm commented
/run pipeline

2024-01-03 17:13 UTC, ocofaigh approved these changes

2024-01-03 17:29 UTC, merged

2024-01-03 17:30 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 7.14.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vpc/releases/tag/v7.14.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: