Terraform example code optimized
terraform-ibm-modules/terraform-ibm-landing-zone-vpc pull request #756
Opened 2024-03-27 12:19 UTC by marifse

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-03-29 11:48 UTC, ocofaigh requested changes
see comments

2024-03-29 11:48 UTC, ocofaigh commented on examples/basic/main.tf
> +  name              = "${var.prefix}-slz-vpc"
no this does't make sense. when you pass a value for prefix, it uses the prefix and name. So var.prefix should not be used here. Can you just set it to `name = vpc` ?

2024-03-29 11:48 UTC, ocofaigh commented on examples/default/main.tf
> +  name                                   = "${var.prefix}-slz-vpc"
same as other comment

2024-03-29 11:48 UTC, ocofaigh commented on examples/no-prefix/main.tf
> +  vpc_name = "noprefix-vpc"
set it to `vpc_name = "vpc"` so it matches what was there before

2024-03-29 13:35 UTC, marifse commented
@ocofaigh please check now

2024-04-03 16:12 UTC, ocofaigh commented
/run pipeline

2024-04-03 16:34 UTC, ocofaigh commented
```
TestRunNoPrefixExample 2024-04-03T16:19:55Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: Value for undeclared variable
│ 
│ A variable named "name" was assigned on the command line, but the root
│ module does not declare a variable of that name. To use this value, add a
│ "variable" block to the configuration.
╵}
```

Test needs to be updated to no longer pass a value for name I guess

2024-04-03 21:49 UTC, marifse commented
@ocofaigh fixed the variable issue, can you please rerun the pipeline. Thanks

2024-04-05 13:50 UTC, ocofaigh commented
/run pipeline

2024-04-05 20:51 UTC, marifse commented
@ocofaigh can you please try rerunning this too

2024-04-05 20:57 UTC, ocofaigh commented
/run pipeline

2024-04-05 21:26 UTC, marifse commented
@ocofaigh sorry to bother, but can you please re run the pipeline.

2024-04-08 08:42 UTC, ocofaigh commented
/run pipeline

2024-04-08 18:01 UTC, ocofaigh approved these changes

2024-04-08 18:01 UTC, merged